spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # 클라이언트 ID
            client-secret: # 클라이언트 보안 비밀번호
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot